require('./deploy-commands.js');
require('./commands/tickets.js');
require('./commands/clear.js');
require('./commands/tos.js');
require('./commands/dev.js');
require('./commands/hacker.js');
require('./commands/rank-up.js');
require('./commands/nitro-boosts.js');
require('./commands/server-boosts.js');